version: '2'
services:
  web:
    image: node
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: "sh -c 'cd /app && npm install && npm start'"
  backend:
    image: hwaterke/hackflix-backend
    ports:
      - "5000:5000"
