version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command: "sh -c 'npm install && npm start'"
  backend:
    image: hwaterke/hackflix-backend
    ports:
      - "5000:5000"
